project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - index.qmd
      - research.qmd
      - media.qmd
      - writing.qmd
      - skateboarding.qmd
      - contact.qmd
  page-footer: 
    right: "Website built with Quarto (https://quarto.org/)"
    left: "&copy; Copyright 2025, Donaven Baughman"

format:
  html: 
    theme: sandstone # different themes can be found at https://quarto.org/docs/output-formats/html-themes.html
    toc: true
    css: styles.css
    
    


