project:
  type: website

website:
  navbar:
    left:
      - home.qmd
      - research.qmd
      - media.qmd
      - writing.qmd
      - skateboarding.qmd
      - contact.qmd

format:
  html: 
    theme: sandstone # different themes can be found at https://quarto.org/docs/output-formats/html-themes.html
    toc: true
    
    

